version: '3.8'

services:
  web:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  php:
    image: php:8.1-fpm
    volumes:
      - ./your-php-files:/var/www/html

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: adile
      POSTGRES_PASSWORD: Alitekin
      POSTGRES_DB: zoo1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
